### ISSUE TITLE
[功能][建议]支持HTTP协议以解决CLEARTEXT通信错误

### ISSUE THREAD

**Issue by A233S** [Skythinker616/gpt-assistant-android#1]
开发者您好，

目前该项目仅支持使用HTTPS协议与API进行交流。当尝试使用HTTP协议时，会遇到以下错误：
```
获取失败: java.net.UnknownServiceException: CLEARTEXT communication to oneapi.run.goorm.site not permitted by network security policy
```
如果我操作上有什么失误，请指出。
感谢！

相关截图 :
![Screenshot_2023-09-15-16-42-22-628_com skythinker gptassistant](https://github.com/Skythinker616/gpt-assistant-android/assets/71011762/f35a61b1-d4f3-4b28-af96-73fad43cea27)
![Screenshot_2023-09-15-16-42-45-347_com skythinker gptassistant](https://github.com/Skythinker616/gpt-assistant-android/assets/71011762/cae1ecd2-533d-4e9b-a88a-f3e261f1ff4c)

**Comment by Skythinker616** [comment]
已更新代码，解除了HTTPS限制，经测试不会再报这个错误，但目前我没有支持HTTP的API服务可用于测试，你可以下载预发布版本测试一下各项功能是否正常
