### ISSUE TITLE
能否记住上下文，语音播放功能的状态？

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#10]

**Comment by Skythinker616** [comment]
经实际使用测试，若软件记住连续对话或语音播报开关状态，在下一次快捷唤起时该状态并不一定是想要的，还需要进行检查或手动调整，不够方便。因此现有逻辑是允许用户将常用的开关状态设置为唤起时的默认状态，在唤起后可以手动修改。
