### ISSUE TITLE
图中的链接是不是markdown格式的，这种链接怎么在app中访问？

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#13]
直接复制链接，app没法解析出来。
![Screenshot_2023-12-09-19-12-47-256_com.skythinker.gptassistant.jpg](https://github.com/Skythinker616/gpt-assistant-android/assets/109005556/fafb36bd-f701-434c-a2df-ec675b1645b3)

**Comment by Skythinker616** [comment]
我不太能理解你的问题，请详细描述你的需求或操作步骤。另外，图中似乎并不是一个完整的GPT回答。

**Comment by xinggonglie** [comment]
我直接给你打录屏，163邮件能不能收



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月9日(周六) 晚上8:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Skythinker616/gpt-assistant-android] 图中的链接是不是markdown格式的，这种链接怎么在app中访问？ (Issue #13)




 
我不太能理解你的问题，请详细描述你的需求或操作步骤。另外，图中似乎并不是一个完整的GPT回答。

**Comment by Skythinker616** [comment]
建议直接在本issue页面上传视频附件
