### ISSUE TITLE
无障碍模式出现故障，按音量键没有反应

### ISSUE THREAD

**Issue by blueblue147** [Skythinker616/gpt-assistant-android#15]
![微信图片_20231211085732](https://github.com/Skythinker616/gpt-assistant-android/assets/109064586/c5432fc3-bc01-42f4-bfba-df907827ba39)

**Comment by Skythinker616** [comment]
你好，请问是否能够提供软件版本、机型、系统版本等信息？

是安装后第一次开启无障碍服务就产生该错误吗？

**Comment by blueblue147** [comment]
软件版本：V1.7.1机型：红米note12turbo
系统版本：MIUI14.0.25
安装后当天可以正常使用，第二天突然产生该错误
&nbsp;


Вася
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月11日(星期一) 中午11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Skythinker616/gpt-assistant-android] 无障碍模式出现故障，按音量键没有反应 (Issue #15)





 
你好，请问是否能够提供软件版本、机型、系统版本等信息？
 
是安装后第一次开启无障碍服务就产生该错误吗？

**Comment by Skythinker616** [comment]
根据你的描述该错误可能与系统有关，请问产生错误之前是否重启过手机，以及是否添加本应用到后台运行白名单？
你可以尝试手动关闭无障碍权限然后再次打开，看看错误有没有恢复。
