### ISSUE TITLE
退出软件时不论设置项是否开启都会保存对话

### ISSUE THREAD

**Issue by A233S** [Skythinker616/gpt-assistant-android#18]
希望在设置中增加一个选项，允许用户关闭聊天记录保存功能

**Comment by A233S** [comment]
目前使用过程中，在向chatgpt聊天之后，点击上方空白处退出程序，仍然可以在历史记录中看到之前的聊天内容。

**Comment by Skythinker616** [comment]
设置中有“自动保存对话”选项呀，默认是开启的，关闭后就不会保留聊天记录了

**Comment by A233S** [comment]
目前测试在聊天之后，点击上方空白处退出程序，仍然可以在历史记录中看到之前的聊天内容。

**Comment by Skythinker616** [comment]
目前的设计就是这样的，在开启保存对话功能后，新建对话和退出软件（包括返回键或点击空白处）的时候都会保存当前会话，即历史记录包含了进行过的所有聊天。你的意思是希望只在新建对话时保存对话吗，这样似乎不太符合逻辑。

**Comment by A233S** [comment]
可能我刚刚表达有误，那我直接通过录屏来向你解释吧。
https://github.com/Skythinker616/gpt-assistant-android/assets/71011762/d5affdfe-58af-4267-8bc5-304b0659a227

**Comment by A233S** [comment]
可能我刚刚表达有误，那我直接通过录屏来向你解释吧。

https://github.com/Skythinker616/gpt-assistant-android/assets/71011762/4ec5f53d-a386-4fa4-bea0-cc13c6e2e6e6

**Comment by A233S** [comment]
在关闭保存对话功能后，仍有少数情况可能导致对话被保存。

**Comment by Skythinker616** [comment]
已复现并定位问题，退出软件时不论设置项是否开启都会保存对话，将在下个版本修复，非常感谢。

**Comment by Skythinker616** [comment]
[v1.8.1](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.8.1) 版本已修复该问题
