### ISSUE TITLE
[功能]优化文本处理性能

### ISSUE THREAD

**Issue by A233S** [Skythinker616/gpt-assistant-android#2]
我在使用时，发现当其输出的文本过长时，程序会出现卡顿现象。这种情况在性能较差的设备上更为明显。

希望能够对文本处理的性能进行优化，以提升更多设备上的使用体验。

感谢！

**Comment by Skythinker616** [comment]
从v1.6.0版本开始接收文本时的渲染频率被限制在10Hz以内，应该可以缓解该问题
