### ISSUE TITLE
按你的提示询问当下北京时间，日期是对的，时间是不对的

### ISSUE THREAD

**Issue by zhl111** [Skythinker616/gpt-assistant-android#20]
如果只是做个示范，就不是个好的例子
![image](https://github.com/Skythinker616/gpt-assistant-android/assets/29135984/f00f6092-f7f0-47a3-9ea1-37a454bca9d9)
第二个问题：
![image](https://github.com/Skythinker616/gpt-assistant-android/assets/29135984/b922b5cc-3ad1-4393-b95d-c5eab6c9502b)
 第三个问题：三星S23 ultra的支持不是很好。即使开了权限，辅助功能，短时间内可以长按下音量键可以唤醒gpt助手，但过一会就无法唤醒了

**Comment by Skythinker616** [comment]
- 关于第一个问题：与示例不一样应该是因为百度页面发生了变化，现在的第一个搜索结果中抓取的文本里看不出明确的时间信息，因此GPT采用了下方其他搜索结果中的错误数据。该问题目前没有很好的解决方案，你可以尝试修改提问让GPT换个网站访问（如“用必应搜索”、“在线获取”等，或在模板中直接写明访问网址）。获取时间算是一个特殊情况，在其他大部分情况下，使用百度搜索的数据还是比较可靠的。
- 关于第二个问题：目前在我的测试中还没有出现该问题，请问你使用的是官方接口还是中转接口，是否使用代理软件，该问题复现率如何？
- 关于第三个问题：可能是软件被杀后台了，你可以尝试在系统设置中把本应用加入后台白名单。
