### ISSUE TITLE
华为mate40pro无法使用音量键唤起，也无法进入语音输入，有没有其他方式进入语音输入模式？

### ISSUE THREAD

**Issue by onion0835** [Skythinker616/gpt-assistant-android#21]
华为mate40pro无法使用音量键唤起，也无法进入语音输入，有没有其他方式进入语音输入模式？

**Comment by Skythinker616** [comment]
请问你确定正确开启了无障碍服务吗？目前没有其他方式可以触发语音输入。
HarmonyOS进入无障碍设置界面后需要点击最下方的“已安装的服务”，然后开启GPTAssistant的权限

**Comment by Skythinker616** [comment]
[v1.10.0](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.10.0) 版本支持长按输入框进行语音输入，你可以尝试一下
