### ISSUE TITLE
提示无障碍功能开启

### ISSUE THREAD

**Issue by brlanweb** [Skythinker616/gpt-assistant-android#22]
手机无障碍分为多组功能，通用‘视觉’听觉等。单独打开通用，或者听觉或者组合打开通用，听觉视觉都还是会持续提示，感觉无解

**Comment by Skythinker616** [comment]
需要开启GPTAssistant这个软件的无障碍服务，这在不同厂商的系统上开启方式不太一样。
例如HarmonyOS中进入无障碍页面后需点击最下方的“已安装的服务”，列出所有可用的软件，在其中开启GPTAssistant的服务。
你的系统是什么？你可以根据你的系统查一下如何开启特定软件的无障碍服务。
