### ISSUE TITLE
[兼容性问题]未预装WebView的少数设备在启动应用时崩溃

### ISSUE THREAD

**Issue by A233S** [Skythinker616/gpt-assistant-android#3]
在少数未预装WebView的设备上，启动此应用程序时会发生崩溃。
如果可能的话，在不使用`启用网络访问`功能的情况下，应用不调用WebView
希望能够使其能在这些设备上正常运行。
相关日志文件:[crash.log](https://gist.github.com/A233S/b1a0a0f976af61a146bcdc481dc6037d)

感谢！

**Comment by Skythinker616** [comment]
v1.6.1版本对此问题进行了修复，在Wear OS虚拟机中进行测试，可以使用问答等基础功能。由于界面元素较多，可以调小dpi后在小屏幕中使用。
