### ISSUE TITLE
全局上下文菜单需要什么设置支持吗

### ISSUE THREAD

**Issue by QAbot-zh** [Skythinker616/gpt-assistant-android#33]
在vivo neo7(android 13) 、华为平板matepad 11(鸿蒙4）下载安装，均无法实现选中文字后出现全局上下文的gpt assistant选项，是否需要打开什么手动设置？

**Comment by QAbot-zh** [comment]
重启后有了，不过不是所有场景都能有这个全局上下文，可能是其他app的限制。

**Comment by Skythinker616** [comment]
> 重启后有了，不过不是所有场景都能有这个全局上下文，可能是其他app的限制。

是的，有些软件覆写了系统上下文菜单，无法使用这个功能。此外，在[v1.10.0](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.10.0)版本中支持通过分享文本唤起软件（即选中文本后点分享），可以支持更多的场景（如华为双指识屏），你可以尝试一下。
