### ISSUE TITLE
建议增加国内大模型接口，解决openai接口无法访问问题

### ISSUE THREAD

**Issue by tocky0** [Skythinker616/gpt-assistant-android#38]
1 建议增加国内大模型（最好也有免费版）,可自行填入appkey
2 另外，其实也建议支持 一句话语音识别（可能交互有调整），而不是实时的语音识别ASR。
一句话这种 语音识别 android手机有自带API，而云厂商的ASR通常要收费

**Comment by Skythinker616** [comment]
1. 在国内可以使用中转商的服务或自建代理，本人自用的中转已在说明文档中推荐。国内的大模型接口我还没有仔细研究，但适配起来似乎是一个不小的工作量，目前暂时没有开发计划。
2. 据我所知国内厂商大多都去掉了安卓的语音识别服务，系统`SpeechRecognizer`接口是无法调用的，只能采用第三方云端接口。在安装Google应用后，即可通过该系统接口调用谷歌的ASR云服务，本项目的Google接口就是这么实现的，但在国内无法直接访问。当前默认的华为接口应该是比较合适的，开箱即用，效果较好而且免费，目前还没有要收费的消息。

**Comment by tocky0** [comment]
感谢！
