### ISSUE TITLE
能否为markdown代码提供复制功能

### ISSUE THREAD

**Issue by QAbot-zh** [Skythinker616/gpt-assistant-android#39]
如题，能否为回复中的markdown代码提供一键复制功能，手动拉文字不方便且格式容易出现问题，很多网页聊天版都有类似的copy代码功能

**Comment by Skythinker616** [comment]
[v1.11.0](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.11.0) 版本添加了该功能，点击代码块即可复制到剪贴板
