### ISSUE TITLE
无法语音对话

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#4]
你好，小米手机，安卓13，打开无障碍后，语音对话无法实现。它无法识别语音的输入，就是输入框里没有文字。
下面有几个问题想请教下：
1.请问你这个app本身的功能，能否实现和chatgpt手机端上的连续对话一样的功能？就是连续进行对话，不需要手动输入。
2.为什么要使用无障碍模式，能不能直接“app收音，音频转文本，文本传大模型，打模型返回文本，文本转语音，语音播放”。这个流程可以实现吗，和现在这种无障碍模式有什么区别？
3.你现在还打算继续这个项目吗？如果把这个项目做些修改，做一些商业化尝试，你有兴趣吗？
希望可以和你沟通。联系方式1848839936@qq.com

**Comment by Skythinker616** [comment]
你好，请问在开启无障碍后，你是否是通过长按音量下键唤起应用，保持按住不放并进行语音输入？在成功识别到文字之前，输入框应该会提示“正在聆听...”。
关于你的问题：
1. 目前没有做官方软件的全自动语音对话，但可以不手动输入文字，仅通过操作音量键进行语音对话。
2. 无障碍模式是为了捕获音量键事件，该事件用于唤起软件并触发语音输入。你说的全自动流程应该可以通过少量修改实现，后续可能会进行尝试。
3. 这个项目目前在本人业余时间不定期更新，暂未考虑过商业化，如果你有什么想法，可以通过邮件联系 bwlan616@163.com。

**Comment by Skythinker616** [comment]
经沟通，问题在于没有正确开启无障碍功能，开启后软件运行正常，本issue关闭。
