### ISSUE TITLE
请问百度asr的api key怎么申请？

### ISSUE THREAD

**Issue by hzhou81** [Skythinker616/gpt-assistant-android#45]
如题所问

**Comment by Skythinker616** [comment]
一般情况不需要配置百度ASR，用默认的华为接口即可；配置百度接口的说明在[项目主页](https://github.com/Skythinker616/gpt-assistant-android?tab=readme-ov-file#3-%E9%85%8D%E7%BD%AE%E8%AF%AD%E9%9F%B3%E8%AF%86%E5%88%AB-%E5%8F%AF%E9%80%89)可以找到
