### ISSUE TITLE
请问下,app不在前台了,就回到初始界面了吗?

### ISSUE THREAD

**Issue by sparkssssssss** [Skythinker616/gpt-assistant-android#49]
今天刚使用,使用自己的api,感觉相比浏览器,方便很多,首先表示感谢!
我目前的问题如下:
1.
没有开启无障碍,就是当前对话,我暂时不用了,点击桌面,app就到后台了,然后等我想用的时候(确定app处于运行中,我在应用管理中可以看到其状态是运行),在打开app,就到了初始打开的界面了,我需要在历史对话中,找到我之前的对话才可以继续之前的对话
我并没有清理这个app,只是没有显示在前台,但是感觉这个操作,似乎和清理了app然后重新打开一样,请指点下
我目前的选项是
![微信图片_20240517115957](https://github.com/Skythinker616/gpt-assistant-android/assets/14211550/df94a455-cd01-4329-8555-599385332416)
2-文字输入款内输入了问题,回车后,输入框内的文字还在输入款内,导致下次输入文字还需要先清除一次

**Comment by Skythinker616** [comment]
1. 我不太确定你的“点击桌面”操作具体是什么，如果是点击对话界面上方的空白区域是会直接退出软件的，与用返回键退出一样；如果希望保留后台，可以通过上划手势（或home键）返回桌面，这和其他应用是一样的
2. 在下个版本会考虑修改为发送后自动清空输入框

**Comment by sparkssssssss** [comment]
> 1. 我不太确定你的“点击桌面”操作具体是什么，如果是点击对话界面上方的空白区域是会直接退出软件的，与用返回键退出一样；如果希望保留后台，可以通过上划手势（或home键）返回桌面，这和其他应用是一样的
> 2. 在下个版本会考虑修改为发送后自动清空输入框

1-明白了,
2-期待更新,谢谢
