### ISSUE TITLE
联网功能异常

### ISSUE THREAD

**Issue by cloudtuotuo** [Skythinker616/gpt-assistant-android#5]
手机：红米 K60
版本：1.70

选用联网功能后，返回错误提示
获取失败:{
"error".
"message":"Invalid schema forfunction 'get html text': None is notof type array“,
"type": "invalid request_error"
param": null
"code": null

**Comment by Skythinker616** [comment]
请问你使用的是官方接口还是哪个中转接口？

**Comment by xinggonglie** [comment]
官方



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月5日(周二) 上午10:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Skythinker616/gpt-assistant-android] 联网功能异常 (Issue #5)




 
请问你使用的是官方接口还是哪个中转接口？

**Comment by Skythinker616** [comment]
[v1.7.1](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.7.1) 版本已修复该问题，若仍发生错误，可随时再开启本issue
