### ISSUE TITLE
dall-e-3模型调用出错

### ISSUE THREAD

**Issue by sparkssssssss** [Skythinker616/gpt-assistant-android#51]
使用最新版本
自定义添加dall-e-3文生图模型
但是在调用的时候,貌似请求是写死的/v1/chat/completions,所以导致无法正确的调用模型
期望能增加一个判断,当为文生图模型的走/v1/images/generations 请求

**Comment by Skythinker616** [comment]
你好，目前本应用还未支持OpenAI文生图模型，可能会在未来版本添加，敬请期待
