### ISSUE TITLE
历史记录再次打开前端模型显示错误

### ISSUE THREAD

**Issue by sparkssssssss** [Skythinker616/gpt-assistant-android#52]
比如当我选择翻译助手进行了对话之后,并保存了对话
下次选择这个历史对话后,界面显示的模型类型似乎当前你的选择,变为了问答,但是实际测试,还是翻译模型
![微信图片_20240523095617](https://github.com/Skythinker616/gpt-assistant-android/assets/14211550/532f0ad1-b30b-44f1-8230-5496443668bf)

**Comment by Skythinker616** [comment]
你的推测没错，恢复历史记录后对话与当前选择的模板无关，仍使用上次的模板。

目前，如文档中所说，在一轮对话中，模板仅在用户发送第一条提问时被代入参数并添加到上下文中，此后就无法修改了，因为代入参数的过程是不可逆的。历史记录会留存所有的上下文（包括代入参数后的模板），因此恢复历史记录后生效的仍是上一次的模板。
