### ISSUE TITLE
GPT输出过程中切换软件到后台导致输出中断

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#6]

**Comment by Skythinker616** [comment]
我这边暂未遇到过，请问是否有复现步骤，复现率如何，可以提供录屏和其他详细信息吗？

**Comment by Skythinker616** [comment]
根据你的录屏，软件输出了报错信息`java.net.SocketException: Software caused connection abort`，因此初步猜测是在GPT输出过程中切到后台导致系统断开了软件的网络连接，触发报错后输出的错误信息覆盖了之前输出了一半的内容。

该错误已在测试设备（Mate30 HarmonyOS4.0 Android12）中复现，并在允许软件后台运行后消失，你可以尝试进行后台设置。后续版本将尝试优化该问题。

**Comment by Skythinker616** [comment]
经测试，该错误主要在较高版本系统上产生，系统会切断后台程序的Socket连接。通过设置将应用添加到后台白名单中可以改善该问题，目前未能找到更好的解决方案。
