### ISSUE TITLE
求教：如何调用github models的api

### ISSUE THREAD

**Issue by sataner** [Skythinker616/gpt-assistant-android#60]
大佬，最近申请下了GitHub models，请问接口地址怎么修改才能调用，感谢！

**Comment by Skythinker616** [comment]
你好，我目前还无法测试GitHub Models，根据官方文档，你可以尝试在接口地址处填写`https://models.inference.ai.azure.com/`，然后在api_key处填写你所创建的[GitHub token](https://github.com/settings/tokens)

**Comment by Skythinker616** [comment]
更新：Github Models 使用的是 Azure OpenAI 接口，不完全兼容 OpenAI 接口，本项目暂时还无法支持

**Comment by sataner** [comment]
在nextchat、oneapi中接口地址可以使用https://models.inference.ai.azure.com/chat/completions#
不过我在gptassistant使用后会程序卡死好像，希望大佬看看

**Comment by Skythinker616** [comment]
> 在nextchat、oneapi中接口地址可以使用https://models.inference.ai.azure.com/chat/completions# 不过我在gptassistant使用后会程序卡死好像，希望大佬看看

非常感谢你的反馈，问题已复现并定位，闪退问题会在后续更新中尝试解决。

经测试，在当前版本可以使用`https://models.inference.ai.azure.com/chat/completions/#/`调用github models，你可以尝试一下。

**Comment by sataner** [comment]
ok啦，感谢大佬，，，

**Comment by Skythinker616** [comment]
闪退问题暂时无法完全解决，但已添加错误捕获防止闪退，已更新在 [v1.11.1](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.11.1) 中，再次感谢你的反馈
