### ISSUE TITLE
使用百度搜索这个功能是怎么实现的？

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#7]
是关键词识别+调用百度的api，返回的网页数据再传给gpt整合文本吗？

**Comment by Skythinker616** [comment]
目前，联网功能是软件向GPT提供Function接口，允许其请求一个网页URL，软件收到该请求后使用WebView访问该网页，然后将网页中的文本和链接内容返回给GPT。

是否使用百度搜索并不是由软件自己决定的，GPT在收到用户问题后会自行决定是否访问网页、访问什么网页。

**Comment by xinggonglie** [comment]
这个和gpt4 的插件功能一样吗，类似于把本地的webview服务作为一个插件调用的api存在？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月8日(周五) 中午11:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Skythinker616/gpt-assistant-android] 使用百度搜索这个功能是怎么实现的？ (Issue #7)




 
目前，联网功能是软件向GPT提供Function接口，允许其请求一个网页URL，软件收到该请求后使用WebView访问该网页，然后将网页中的文本和链接内容返回给GPT。
 
是否使用百度搜索并不是由软件自己决定的，GPT在收到用户问题后会自行决定是否访问网页、访问什么网页。

**Comment by Skythinker616** [comment]
是的，就相当于把本地WebView作为一个插件，跟官方GPT4基本原理差不太多，不过目前只是简单地把GPT请求的网页内容直接返回回去，没有进一步访问搜索结果，因此无法完成太复杂的检索任务。
