### ISSUE TITLE
能不能把加在system和user的预设文本从功能上分开？

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#8]
一个作为角色模板，一个是prompt模板

**Comment by Skythinker616** [comment]
考虑到本软件大部分场景并不需要指定全局prompt，目前并未使用system角色，prompt模板和用户输入均被添加至user中，这样也可以让模板作用效果更明显。全局角色模板的需求应该不大，暂不考虑添加，如未来发现有较多应用场景则可能会再添加。

**Comment by xinggonglie** [comment]
是不是可以这样理解，app是把模板和输入对话的内容，合成一段文字，按照user的身份，一起发给gpt？
你看我图片中，如果我想实现利用模板不断的检索、总结资料，现有的设置，只有单独一次对话时表现可以，连续对话后，我写的这个百度的模板就不能检索了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月8日(周五) 中午11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Skythinker616/gpt-assistant-android] 能不能把加在system和user的预设文本从功能上分开？ (Issue #8)




 
考虑到本软件大部分场景并不需要指定全局prompt，目前并未使用system角色，prompt模板和用户输入均被添加至user中，这样也可以让模板作用效果更明显。全局角色模板的需求应该不大，暂不考虑添加，如未来发现有较多应用场景则可能会再添加。

**Comment by Skythinker616** [comment]
1. 你的理解没有问题
2. 好像没有找到你发的图片

**Comment by xinggonglie** [comment]
![Screenshot_2023-12-08-15-24-33-312_com.skythinker.gptassistant.jpg](https://github.com/Skythinker616/gpt-assistant-android/assets/109005556/a3b8b0c7-e6fd-446f-81af-e8601a24c905)

![Screenshot_2023-12-08-14-02-18-581_com.skythinker.gptassistant.jpg](https://github.com/Skythinker616/gpt-assistant-android/assets/109005556/6d7174cc-970f-4497-adce-55c1f838d939)

![Screenshot_2023-12-08-15-21-42-102_com.skythinker.gptassistant.jpg](https://github.com/Skythinker616/gpt-assistant-android/assets/109005556/05bcb22a-220d-42c4-b745-6703025bd07b)

![Screenshot_2023-12-08-13-33-57-125_com.skythinker.gptassistant.jpg](https://github.com/Skythinker616/gpt-assistant-android/assets/109005556/5abc0ef7-a67d-4378-9aa1-935279ef1ec1)

**Comment by xinggonglie** [comment]
顺序反了，最下面是图1

**Comment by Skythinker616** [comment]
可以理解你的意思，后续会对全局prompt在类似场景下的效果进行测试。

**Comment by Skythinker616** [comment]
[v1.9.0](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.9.0) 版本新增高级模板语法，可以将模板设定为system角色
