### ISSUE TITLE
是否可以保存历史对话记录？

### ISSUE THREAD

**Issue by xinggonglie** [Skythinker616/gpt-assistant-android#9]
这个功能和支持上下文对话的功能区分开来。当然支持官方网页那种tab更好。

**Comment by Skythinker616** [comment]
已在 TODO 列表中

**Comment by Skythinker616** [comment]
[v1.8.0](https://github.com/Skythinker616/gpt-assistant-android/releases/tag/v1.8.0) 版本已支持历史记录功能
